server:
  port: 8081
spring:
  application:
    name: user

eureka:
  client:
    service-url:
      defaultZone: http://nick:123456@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"